import asyncio
import logging
import websockets
import random
from datetime import datetime, timezone
from fastapi import FastAPI, HTTPException
from uvicorn import Config, Server

from ocpp.routing import on
from ocpp.v21 import ChargePoint as cp
from ocpp.v21 import call, call_result
from ocpp.v21.enums import Action

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger("ocpp_server_api")

active_chargers = {}


def generate_id():
    # Returns a random integer between 1 and 2 billion
    return random.randint(1, 2147483647)


class ChargePoint(cp):
    @on(Action.boot_notification)
    async def on_boot_notification(self, charging_station, reason, **kwargs):
        logger.info(
            f"[{self.id}] Boot: {charging_station.get('vendor_name')} | Reason: {reason}"
        )
        return call_result.BootNotification(
            current_time=datetime.now(timezone.utc).isoformat(),
            interval=10,
            status="Accepted",
        )

    @on(Action.heartbeat)
    async def on_heartbeat(self):
        return call_result.Heartbeat(
            current_time=datetime.now(timezone.utc).isoformat()
        )

    @on(Action.transaction_event)
     async def on_transaction_event(self, event_type, timestamp, trigger_reason, seq_no, transaction_info, **kwargs):
        # Extract the ID generated by the charger
        tx_id = transaction_info['transactionId']

        # Save it so the API knows which ID to use for 'Stop'
        # We store it in a way that maps evse_id -> transaction_id
        evse_id = kwargs.get('evse', {}).get('id', 1)

        if event_type == "Started":
            logger.info(f"[{self.id}] Transaction STARTED. ID: {tx_id}")
            self.active_transactions[evse_id] = tx_id
                
        elif event_type == "Ended":
            logger.info(f"[{self.id}] Transaction ENDED. ID: {tx_id}")
            if evse_id in self.active_transactions:
                del self.active_transactions[evse_id]
        return call_result.TransactionEvent()

    def __init__(self, id, connection):
        super().__init__(id, connection)
        self.active_transactions = {} # Mapping of evse_id: transaction_id

app = FastAPI(title="CSMS API")


@app.get("/chargers")
async def list_chargers():
    """Returns a list of all currently connected charger IDs."""
    return {"connected_chargers": list(active_chargers.keys())}


@app.post("/remote-start/{cp_id}/{evsd_id}")
async def remote_start(cp_id: str, evse_id: int):
    """Triggers a RequestStartTransaction command to a specific charger."""
    if cp_id not in active_chargers:
        raise HTTPException(
            status_code=404, detail=f"Charger {cp_id} not found/connected."
        )

    charger = active_chargers[cp_id]

    request = call.RequestStartTransaction(
        remote_start_id=generate_id(),
        evse_id=evse_id,  # <--- This tells the box which cable to unlock
    )

    try:
        response = await charger.call(request)
        return {"status": response.status, "charger_id": cp_id}
    except Exception as e:
        logger.error(f"Failed to send command to {cp_id}: {e}")
        raise HTTPException(status_code=500, detail="OCPP Command Timeout")


@app.post("/remote-stop/{cp_id}/{transaction_id}")
async def remote_stop(cp_id: str, transaction_id: str):
    """Tells a charger to stop a specific active transaction."""
    if cp_id not in active_chargers:
        raise HTTPException(status_code=404, detail="Charger not connected")

    charger = active_chargers[cp_id]

    # OCPP 2.1 message to stop a transaction
    request = call.RequestStopTransaction(transaction_id=transaction_id)

    response = await charger.call(request)
    return {"status": response.status, "transaction_id": transaction_id}


# WebSocket Handler
async def on_connect(websocket):
    cp_id = websocket.request.path.strip("/")
    charger = ChargePoint(cp_id, websocket)

    # Register the charger in our global dict
    active_chargers[cp_id] = charger
    logger.info(f"[{cp_id}] Connected and registered in API state.")

    try:
        await charger.start()
    finally:
        # Unregister when the charger disconnects
        if cp_id in active_chargers:
            del active_chargers[cp_id]
        logger.warning(f"[{cp_id}] Disconnected and removed from API state.")


async def main():
    # WebSocket Server (Port 9000)
    ws_server = websockets.serve(on_connect, "0.0.0.0", 9000, subprotocols=["ocpp2.1"])

    # FastAPI Server (Port 8000)
    config = Config(app=app, host="0.0.0.0", port=8000, loop="asyncio")
    api_server = Server(config)

    logger.info("Starting Multi-Protocol Server (OCPP: 9000, API: 8000)")

    await asyncio.gather(ws_server, api_server.serve())


if __name__ == "__main__":
    asyncio.run(main())
